app/routes/auth.py
from flask import Blueprint, session, redirect, render_template, url_for, request

from app.databases import db

from app.models import User

auth = Blueprint('auth', __name__)

@auth.route('/signup', methods=['GET','POST'])
def signup():
    if request.method == 'POST':
        username = request.form['username']
        password = request.form['password']
        name = request.form['name']
        last_name = request.form['surname']
        email = request.form['email']
        phone = request.form['phone']
        user = User(username=username,
                    password=password,
                    email=email,
                    first_name=name,
                    last_name=last_name,
                    phone=phone)
        db.session.add(user)
        db.session.commit()
        session['user_id'] = user.id
        return redirect(url_for('home'))
    else:
        return render_template('signup.html')
    
@auth.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        username = request.form['username']
        password = request.form['password']
        user = User.query.filter_by(username=username, password=password).first()
        if user:
            session['user_id'] = user.id
        return redirect(url_for('home'))
    else:
        return render_template('login.html')

@auth.route('/logout')
def logout():
    session.pop('user_id', None)
    return redirect(url_for('home'))

app/routes/user.py
from flask import Blueprint, session, redirect, render_template, url_for, request
import random

from app.databases import db

from app.models import User, SearchHistory, FriendRequest

user = Blueprint('user', __name__, url_prefix='/user')

@user.route('/search_history', methods=['GET'])
def search_history():
    if 'user_id' in session:
        user_id = session['user_id']
        user = User.query.get(user_id)
        if user:
            searches = SearchHistory.query.filter_by(usuario_id=user_id).all()
            return render_template('search_history.html', user=user, searches=searches, random=random)
        return redirect(url_for('home'))
    else:
        return redirect(url_for('home'))
    
@user.route('/profile/search_users', methods=['GET', 'POST'])
def search_users():
    if request.method == 'POST':
        search_query = request.form.get('search_query')
        if search_query:
            users = User.query.filter(User.username.ilike(f'%{search_query}%')).all()
            return render_template('search_users.html', users=users)
    return redirect(url_for('home'))
    
@user.route('/profile/<int:user_id>', methods=['GET', 'POST'])
def profile(user_id):
    print('profile')
    if 'user_id' in session:
        user = User.query.get(user_id)
        friend_requests_received = FriendRequest.query.filter_by(receiver_id=user_id, status='pending').all()
        # find friends
        friendsAccepted = FriendRequest.query.filter_by(sender_id=user_id, status='accepted').all()
        friends = User.query.filter(User.id.in_([friend.receiver_id for friend in friendsAccepted])).all()
        if request.method == 'POST':
            sender_id = user.id
            receiver_username = request.form['receiver_username']
            receiver = User.query.filter_by(username=receiver_username).first()
            if receiver:
                # Verificar si ya existe una solicitud pendiente entre los usuarios
                existing_request = FriendRequest.query.filter_by(sender_id=sender_id, receiver_id=receiver.id).first()
                if not existing_request:
                    new_request = FriendRequest(sender_id=sender_id, receiver_id=receiver.id)
                    db.session.add(new_request)
                    db.session.commit()
        return render_template('profile.html', user=user, friend_requests_received=friend_requests_received, friends=friends, random=random)
    else:
        return redirect(url_for('auth.login'))
    
@user.route('/send_friend_request/<int:receiver_id>', methods=['POST'])
def send_friend_request(receiver_id):
    if 'user_id' in session:
        sender_id = session['user_id']
        friend_request = FriendRequest(sender_id=sender_id, receiver_id=receiver_id)
        db.session.add(friend_request)
        db.session.commit()
    return redirect(url_for('home'))

@user.route('/accept_friend_request/<int:request_id>', methods=['POST'])
def accept_friend_request(request_id):
    if 'user_id' in session:
        user_id = session['user_id']
        friend_request = FriendRequest.query.get(request_id)
        if friend_request and friend_request.receiver_id == user_id:
            friend_request.status = 'accepted'
            db.session.commit()
    return redirect(url_for('home'))

@user.route('/reject_friend_request/<int:request_id>', methods=['POST'])
def reject_friend_request(request_id):
    if 'user_id' in session:
        user_id = session['user_id']
        friend_request = FriendRequest.query.get(request_id)
        if friend_request and friend_request.receiver_id == user_id:
            friend_request.status = 'rejected'
            db.session.commit()
    return redirect(url_for('home'))

app/templates/components/footer.html
<footer
  class="footer footer-center p-10 bg-primary text-primary-content rounded"
>
  <aside>
    <svg
      width="50"
      height="50"
      viewBox="0 0 24 24"
      xmlns="http://www.w3.org/2000/svg"
      fill-rule="evenodd"
      clip-rule="evenodd"
      class="inline-block fill-current"
    >
      <path
        d="M22.672 15.226l-2.432.811.841 2.515c.33 1.019-.209 2.127-1.23 2.456-1.15.325-2.148-.321-2.463-1.226l-.84-2.518-5.013 1.677.84 2.517c.391 1.203-.434 2.542-1.831 2.542-.88 0-1.601-.564-1.86-1.314l-.842-2.516-2.431.809c-1.135.328-2.145-.317-2.463-1.229-.329-1.018.211-2.127 1.231-2.456l2.432-.809-1.621-4.823-2.432.808c-1.355.384-2.558-.59-2.558-1.839 0-.817.509-1.582 1.327-1.846l2.433-.809-.842-2.515c-.33-1.02.211-2.129 1.232-2.458 1.02-.329 2.13.209 2.461 1.229l.842 2.515 5.011-1.677-.839-2.517c-.403-1.238.484-2.553 1.843-2.553.819 0 1.585.509 1.85 1.326l.841 2.517 2.431-.81c1.02-.33 2.131.211 2.461 1.229.332 1.018-.21 2.126-1.23 2.456l-2.433.809 1.622 4.823 2.433-.809c1.242-.401 2.557.484 2.557 1.838 0 .819-.51 1.583-1.328 1.847m-8.992-6.428l-5.01 1.675 1.619 4.828 5.011-1.674-1.62-4.829z"
      ></path>
    </svg>
    <p class="font-bold">
      RM & A Industries Ltd. <br />Providing reliable tech since 2023
    </p>
    <p>Copyright © 2024 - All right reserved</p>
  </aside>
  <nav>
    <div class="grid grid-flow-col gap-4">
      <a
        ><svg
          xmlns="http://www.w3.org/2000/svg"
          width="24"
          height="24"
          viewBox="0 0 24 24"
          class="fill-current"
        >
          <path
            d="M24 4.557c-.883.392-1.832.656-2.828.775 1.017-.609 1.798-1.574 2.165-2.724-.951.564-2.005.974-3.127 1.195-.897-.957-2.178-1.555-3.594-1.555-3.179 0-5.515 2.966-4.797 6.045-4.091-.205-7.719-2.165-10.148-5.144-1.29 2.213-.669 5.108 1.523 6.574-.806-.026-1.566-.247-2.229-.616-.054 2.281 1.581 4.415 3.949 4.89-.693.188-1.452.232-2.224.084.626 1.956 2.444 3.379 4.6 3.419-2.07 1.623-4.678 2.348-7.29 2.04 2.179 1.397 4.768 2.212 7.548 2.212 9.142 0 14.307-7.721 13.995-14.646.962-.695 1.797-1.562 2.457-2.549z"
          ></path></svg
      ></a>
      <a
        ><svg
          xmlns="http://www.w3.org/2000/svg"
          width="24"
          height="24"
          viewBox="0 0 24 24"
          class="fill-current"
        >
          <path
            d="M19.615 3.184c-3.604-.246-11.631-.245-15.23 0-3.897.266-4.356 2.62-4.385 8.816.029 6.185.484 8.549 4.385 8.816 3.6.245 11.626.246 15.23 0 3.897-.266 4.356-2.62 4.385-8.816-.029-6.185-.484-8.549-4.385-8.816zm-10.615 12.816v-8l8 3.993-8 4.007z"
          ></path></svg
      ></a>
      <a
        ><svg
          xmlns="http://www.w3.org/2000/svg"
          width="24"
          height="24"
          viewBox="0 0 24 24"
          class="fill-current"
        >
          <path
            d="M9 8h-3v4h3v12h5v-12h3.642l.358-4h-4v-1.667c0-.955.192-1.333 1.115-1.333h2.885v-5h-3.808c-3.596 0-5.192 1.583-5.192 4.615v3.385z"
          ></path></svg
      ></a>
    </div>
  </nav>
</footer>

app/templates/components/navbar.html
<div
  class="navbar bg-gradient-to-r from-primary to-purple-600 text-white shadow-lg"
  style="background-size: 200% 200%; animation: moveGradient 8s ease infinite"
>
  <div class="navbar-start">
    <div class="dropdown">
      <div tabindex="0" role="button" class="btn btn-ghost btn-circle">
        <svg
          xmlns="http://www.w3.org/2000/svg"
          class="h-5 w-5"
          fill="none"
          viewBox="0 0 24 24"
          stroke="currentColor"
        >
          <path
            stroke-linecap="round"
            stroke-linejoin="round"
            stroke-width="2"
            d="M4 6h16M4 12h16M4 18h7"
          />
        </svg>
      </div>
      <ul
        tabindex="0"
        class="menu menu-sm dropdown-content mt-3 z-[1] p-2 text-black shadow bg-base-100 rounded-box w-52"
      >
        <li><a href="{{ url_for('home') }}">Home</a></li>
        {% if user %}
        <li>
          <a href="{{ url_for('user.profile', user_id=user.id) }}">Profile</a>
        </li>
        <li>
          <a href="{{ url_for('user.search_history') }}">Search History</a>
        </li>
        <li><a href="{{ url_for('auth.logout') }}">Logout</a></li>
        {% else %}
        <li><a href="{{ url_for('auth.login') }}">Login</a></li>
        <li><a href="{{ url_for('auth.signup') }}">Register</a></li>
        {% endif %}
      </ul>
    </div>
  </div>
  <div class="navbar-center">
    {% if user %}
    <a class="btn btn-ghost text-xl">Welcome , {{ user.username }}!</a>
    {% else %}
    <a class="btn btn-ghost text-xl">SkyTech</a>
    {% endif %}
  </div>

  <div class="navbar-end">
    {% if user and user.searches and random.randint(1,2) == 1 %}
    <div class="dropdown dropdown-end">
      <div tabindex="0" role="button" class="btn btn-ghost btn-circle">
        <div class="indicator">
          <svg
            xmlns="http://www.w3.org/2000/svg"
            class="h-5 w-5"
            fill="none"
            viewBox="0 0 24 24"
            stroke="currentColor"
          >
            <path
              stroke-linecap="round"
              stroke-linejoin="round"
              stroke-width="2"
              d="M15 17h5l-1.405-1.405A2.032 2.032 0 0118 14.158V11a6.002 6.002 0 00-4-5.659V5a2 2 0 10-4 0v.341C7.67 6.165 6 8.388 6 11v3.159c0 .538-.214 1.055-.595 1.436L4 17h5m6 0v1a3 3 0 11-6 0v-1m6 0H9"
            />
          </svg>
          <span class="badge badge-xs indicator-item"></span>
        </div>
      </div>
      <div
        tabindex="0"
        class="mt-3 z-[1] card card-compact dropdown-content w-72 bg-base-100 shadow"
      >
        <div class="card-body">
          <span class="font-bold text-lg text-black">Flight Notifications</span>

          {% for search in user.searches %} {% if loop.index == 1 or
          random.randint(1, 4) == 1 %} {% set google_search_url =
          "https://www.google.com/search?q=flights+from+" ~ search.origin ~
          "+to+" ~ search.destination %} {% set sentences = [ "Don't miss out on
          our limited-time offer! Book your flights from
          <strong>" ~ search.origin ~ "</strong> to
          <strong>" ~ search.destination ~ "</strong> now and save big!",
          "Planning your next adventure? Check out our discounted fares for
          flights between <strong>" ~ search.origin ~ "</strong> and
          <strong>" ~ search.destination ~ "</strong>! Book today and start
          packing!", "Ready to explore? Discover amazing deals on flights from
          <strong>" ~ search.origin ~ "</strong> to
          <strong>" ~ search.destination ~ "</strong>! Reserve your seats now
          and embark on a journey of discovery!", "Unlock new destinations! Book
          your flights from <strong>" ~ search.origin ~ "</strong> to
          <strong>" ~ search.destination ~ "</strong> and let the adventure
          begin! Don't wait, book now!", "Adventure is calling! Take advantage
          of our special fares for flights between
          <strong>" ~ search.origin ~ "</strong> and
          <strong>" ~ search.destination ~ "</strong>! Book now and make
          memories to last a lifetime!", "Dreaming of your next getaway? Look no
          further! Our flights from <strong>" ~ search.origin ~ "</strong> to
          <strong>" ~ search.destination ~ "</strong> offer unbeatable value and
          unforgettable experiences!", "Start your journey with us! Experience
          the magic of travel with our flights from
          <strong>" ~ search.origin ~ "</strong> to
          <strong>" ~ search.destination ~ "</strong>! Book now and let the
          adventure begin!", "Explore the world with ease! Our flights from
          <strong>" ~ search.origin ~ "</strong> to
          <strong>" ~ search.destination ~ "</strong> provide seamless
          connections and unforgettable experiences. Book your tickets now!",
          "Elevate your travel experience! Discover incredible destinations with
          our flights from <strong>" ~ search.origin ~ "</strong> to
          <strong>" ~ search.destination ~ "</strong>! Book today and create
          memories that last a lifetime!", "Adventure awaits! Book your flights
          from <strong>" ~ search.origin ~ "</strong> to
          <strong>" ~ search.destination ~ "</strong> now and embark on an
          unforgettable journey filled with excitement and discovery!",
          "Discover new horizons! With our flights from
          <strong>" ~ search.origin ~ "</strong> to
          <strong>" ~ search.destination ~ "</strong>, the possibilities are
          endless. Book now and start exploring!", "Make every moment count!
          Book your flights from <strong>" ~ search.origin ~ "</strong> to
          <strong>" ~ search.destination ~ "</strong> today and create memories
          that will last a lifetime!", "Escape to paradise! Our flights from
          <strong>" ~ search.origin ~ "</strong> to
          <strong>" ~ search.destination ~ "</strong> offer the perfect
          opportunity to unwind and explore. Book now and experience the
          magic!", "Experience the world in style! Book your flights from
          <strong>" ~ search.origin ~ "</strong> to
          <strong>" ~ search.destination ~ "</strong> and enjoy premium service
          and exclusive amenities. Don't miss out, book today!", "Travel with
          confidence! Our flights from <strong>" ~ search.origin ~ "</strong> to
          <strong>" ~ search.destination ~ "</strong> offer flexible booking
          options and enhanced safety measures. Book now and enjoy peace of
          mind!" ] %} {% set selected_sentence = random.choice(sentences) %}
          <span class="text-info"
            >{{ selected_sentence|safe }}
            <a
              href="{{ google_search_url }}"
              class="text-sky-500 hover:text-sky-700 underline decoration-sky-500"
              >Click here for more information</a
            ></span
          >
          {% endif %} {% endfor %}

          <div class="card-actions">
            <button class="btn btn-primary btn-block">View more</button>
          </div>
        </div>
      </div>
    </div>
    {% endif %}

    <label class="flex cursor-pointer gap-2">
      <svg
        xmlns="http://www.w3.org/2000/svg"
        width="20"
        height="20"
        viewBox="0 0 24 24"
        fill="none"
        stroke="currentColor"
        stroke-width="2"
        stroke-linecap="round"
        stroke-linejoin="round"
      >
        <circle cx="12" cy="12" r="5" />
        <path
          d="M12 1v2M12 21v2M4.2 4.2l1.4 1.4M18.4 18.4l1.4 1.4M1 12h2M21 12h2M4.2 19.8l1.4-1.4M18.4 5.6l1.4-1.4"
        />
      </svg>
      <input type="checkbox" value="forest" class="toggle theme-controller" />
      <svg
        xmlns="http://www.w3.org/2000/svg"
        width="20"
        height="20"
        viewBox="0 0 24 24"
        fill="none"
        stroke="currentColor"
        stroke-width="2"
        stroke-linecap="round"
        stroke-linejoin="round"
      >
        <path d="M21 12.79A9 9 0 1 1 11.21 3 7 7 0 0 0 21 12.79z"></path>
      </svg>
    </label>
  </div>
</div>