app/models/searchHistory.py
from app.databases.connection import db

class SearchHistory(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    origin = db.Column(db.String(50), nullable=False)
    destination = db.Column(db.String(50), nullable=False)
    departure_date = db.Column(db.Date, nullable=False)
    return_date = db.Column(db.Date, nullable=False)
    usuario_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False)

app/routes/auth.py
from flask import Blueprint, session, redirect, render_template, url_for, request

from app.databases import db

from app.models import User

auth = Blueprint('auth', __name__)

@auth.route('/signup', methods=['GET','POST'])
def signup():
    if request.method == 'POST':
        username = request.form['username']
        password = request.form['password']
        name = request.form['name']
        last_name = request.form['surname']
        email = request.form['email']
        phone = request.form['phone']
        user = User(username=username,
                    password=password,
                    email=email,
                    first_name=name,
                    last_name=last_name,
                    phone=phone)
        db.session.add(user)
        db.session.commit()
        session['user_id'] = user.id
        return redirect(url_for('home'))
    else:
        return render_template('signup.html')
    
@auth.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        username = request.form['username']
        password = request.form['password']
        user = User.query.filter_by(username=username, password=password).first()
        if user:
            session['user_id'] = user.id
        return redirect(url_for('home'))
    else:
        return render_template('login.html')

@auth.route('/logout')
def logout():
    session.pop('user_id', None)
    return redirect(url_for('home'))

app/routes/search_flights.py
from flask import Blueprint, session, redirect, render_template, url_for, request

import re
from datetime import datetime, date

from app.databases import db

from app.models import User, Flight, SearchHistory

from app.scrapers import LatamScraper

from openai import OpenAI

client = OpenAI(api_key='.')

search_flights = Blueprint('search_flights', __name__)

@search_flights.route('/search', methods=['POST'])
def search():

    if 'user_id' not in session:
        return redirect(url_for('auth.login'))
    
    query = request.form['search']
    
    if query == '':
        return redirect(url_for('home'))
    
    flight_info = obtener_datos_vuelo(query)

    if isinstance(flight_info, str):  # In case of error or missing information
        print(flight_info)
        return redirect(url_for('home'))

    origin = flight_info['origen']
    destination = flight_info['destino']
    departure_date = datetime.strptime(flight_info['fecha_ida'], '%d/%m').replace(year=datetime.now().year).date()
    return_date = datetime.strptime(flight_info['fecha_vuelta'], '%d/%m').replace(year=datetime.now().year).date() if 'fecha_vuelta' in flight_info else None


    '''
    ### Parsed Query ### 
    date_matches = re.findall(r'(jan|feb|mar|apr|may|jun|jul|aug|sep|oct|nov|dec)\s+(\d{1,2})', query, re.IGNORECASE)
    parsed_dates = []
    for match in date_matches:
        try:
            month, day = match
            date_str = f'{day} {month} {datetime.now().year}'
            parsed_date = datetime.strptime(date_str, '%d %b %Y').date()
            parsed_dates.append(date(parsed_date.year, parsed_date.month, parsed_date.day))
        except ValueError as e:
            print(f"Error al parsear la fecha: {e}")
            continue

    origin, destination = query.split(' to ', 1) # Format of query shall be 'origin to destination'
    destination =  destination.split(' ', 1)[0]
    departure_date, return_date = parsed_dates
    '''
    print(origin, destination, departure_date, return_date)
    
    #departure_date = (datetime.now() + timedelta(days=1)).strftime('%d %m %Y')
    #return_date = (datetime.now() + timedelta(days=2)).strftime('%d %m %Y')

    ### Save Query in History ###
    if 'user_id' in session:
        user_id = session['user_id']
        user = User.query.get(user_id)
        if user:
            new_search = SearchHistory(
                origin=origin,
                destination=destination,
                departure_date=departure_date,
                return_date=return_date,
                usuario_id=user.id,
            )
            db.session.add(new_search)
            db.session.commit()
        
        return redirect(url_for('search_flights.search_results',
                        origin=origin,
                        destination=destination,
                        departure_date=departure_date,
                        return_date=return_date))

    
    return redirect(url_for('auth.signup')) 
  
@search_flights.route('/search_results', methods=['GET'])
def search_results():

    origin = request.args.get('origin')
    destination = request.args.get('destination')
    departure_date = datetime.strptime(request.args.get('departure_date'), '%Y-%m-%d').date()
    return_date = datetime.strptime(request.args.get('return_date'), '%Y-%m-%d').date()

    print("OK:", origin, destination, departure_date, return_date)

    query = Flight.query

    dict_of_acronyms = {
        'Arequipa':'AQP',
        'Cuzco':'CUZ',
        'Lima':'LIM',
        'Piura':'PIU',
        'Tumbes':'TBP'
    }

    if origin:
        query = query.filter(Flight.origin == dict_of_acronyms[origin])
    
    if destination:
        query = query.filter(Flight.destination == dict_of_acronyms[destination])

    if departure_date:
        query = query.filter(Flight.departure_date == departure_date)

    # Obtener el vuelo más barato
    cheapest_flight = query.order_by(Flight.price).first()

    if not cheapest_flight:
        # Scraper
        scraper = LatamScraper(
            origin=origin,
            destination=destination,
            departure_date=departure_date,
            return_date=return_date,
        )

        scraper.scrape()
        flights_data = scraper.save()

        for flight_info in flights_data:
            flight = Flight(
                origin=flight_info['details'][0]['origin'],
                destination=flight_info['details'][0]['destination'],
                price=flight_info['price'],
                duration=flight_info['duration'],
                departure_date=datetime.strptime(flight_info['departure_date'], '%Y-%m-%d').date(),
                departure_time=datetime.strptime(flight_info['departure_time'], '%H:%M').time(),
                arrival_date=datetime.strptime(flight_info['arrival_date'], '%Y-%m-%d').date(),
                arrival_time=datetime.strptime(flight_info['arrival_time'], '%H:%M').time(),
                scales=flight_info['scales']
            )
            db.session.add(flight)

        db.session.commit()

        cheapest_flight = query.order_by(Flight.price).first()
    
    if cheapest_flight:
        keys = ["id", "price", "duration", "departure_date", "departure_time", "arrival_date", "arrival_time", "scales", "origin", "destination"]
        documents = [dict(zip(keys, [getattr(cheapest_flight, key) for key in keys]))]
    else:
        documents = []

    return render_template("search_results.html", query="Flight Results", documents=documents)

  
    '''
@search_flights.route('/search_results', methods=['GET'])
def search_results():

    origin = request.args.get('origin')
    destination = request.args.get('destination')
    departure_date = datetime.strptime(request.args.get('departure_date'), '%Y-%m-%d').date()
    return_date =  datetime.strptime(request.args.get('return_date'), '%Y-%m-%d').date()

    print("OK:" , origin, destination, departure_date, return_date)

    query = Flight.query

    dict_of_acronyms = {
    'Arequipa':'AQP',
    'Cuzco':'CUZ',
    'Lima':'LIM',
    'Piura':'PIU',
    'Tumbes':'TBP'
    }

    if origin:
        query = query.filter(Flight.origin == dict_of_acronyms[origin])
    
    if destination:
        query = query.filter(Flight.destination == dict_of_acronyms[destination])

    if departure_date:
        query = query.filter(Flight.departure_date == departure_date)


        cheapest_flight = query.order_by(Flight.price).first()

    if not cheapest_flight:
        # Scraper
        scraper = LatamScraper(
            origin=origin,
            destination=destination,
            departure_date=departure_date,
            return_date=return_date,
        )

        scraper.scrape()
        flights_data = scraper.save()

        for flight_info in flights_data:
            flight = Flight(
                origin=flight_info['details'][0]['origin'],
                destination=flight_info['details'][0]['destination'],
                price=flight_info['price'],
                duration=flight_info['duration'],
                departure_date=datetime.strptime(flight_info['departure_date'], '%Y-%m-%d').date(),
                departure_time=datetime.strptime(flight_info['departure_time'], '%H:%M').time(),
                arrival_date=datetime.strptime(flight_info['arrival_date'], '%Y-%m-%d').date(),
                arrival_time=datetime.strptime(flight_info['arrival_time'], '%H:%M').time(),
                scales=flight_info['scales']
            )
            db.session.add(flight)

        db.session.commit()

        cheapest_flight = query.order_by(Flight.price).first()
    
    if cheapest_flight:
        keys = ["id", "price", "duration", "departure_date", "departure_time", "arrival_date", "arrival_time", "scales"]
        documents = [dict(zip(keys, [getattr(cheapest_flight, key) for key in keys]))]
    else:
        documents = []

    return render_template("search_results.html", query="Flight Results", documents=documents)


    flights = query.order_by(Flight.departure_date).all()

    if not flights:
        # Scraper
        scraper = LatamScraper(origin=origin,
                       destination=destination,
                       departure_date=departure_date,
                       return_date=return_date,
        )

        scraper.scrape()
        flights_data = scraper.save()

        for flight_info in flights_data:
            flight = Flight(
                origin=flight_info['details'][0]['origin'],
                destination=flight_info['details'][0]['destination'],
                price=flight_info['price'],
                duration=flight_info['duration'],
                departure_date=datetime.strptime(flight_info['departure_date'], '%Y-%m-%d').date(),
                departure_time=datetime.strptime(flight_info['departure_time'], '%H:%M').time(),
                arrival_date=datetime.strptime(flight_info['arrival_date'], '%Y-%m-%d').date(),
                arrival_time=datetime.strptime(flight_info['arrival_time'], '%H:%M').time(),
                scales=flight_info['scales']
            )
            db.session.add(flight)

        db.session.commit()

        query = Flight.query

        if origin:
            query = query.filter(Flight.origin == dict_of_acronyms[origin])
    
        if destination:
            query = query.filter(Flight.destination == dict_of_acronyms[destination])

        if departure_date:
            query = query.filter(Flight.departure_date == departure_date)

        flights = query.order_by(Flight.departure_date).all()
    
    keys = ["id", "price", "duration", "departure_date", "departure_time", "arrival_date", "arrival_time", "scales"]
    documents = [dict(zip(keys, [getattr(flight, key) for key in keys])) for flight in flights]

    return render_template("search_results.html", query="Flights Results", documents=documents)  
'''

def obtener_datos_vuelo(consulta):
    try:
        response = client.chat.completions.create(

app/routes/user.py
from flask import Blueprint, session, redirect, render_template, url_for, request
import random

from app.databases import db

from app.models import User, SearchHistory, FriendRequest

user = Blueprint('user', __name__, url_prefix='/user')

@user.route('/search_history', methods=['GET'])
def search_history():
    if 'user_id' in session:
        user_id = session['user_id']
        user = User.query.get(user_id)
        if user:
            searches = SearchHistory.query.filter_by(usuario_id=user_id).all()
            return render_template('search_history.html', user=user, searches=searches, random=random)
        return redirect(url_for('home'))
    else:
        return redirect(url_for('home'))
    
@user.route('/profile/search_users', methods=['GET', 'POST'])
def search_users():
    if request.method == 'POST':
        search_query = request.form.get('search_query')
        if search_query:
            users = User.query.filter(User.username.ilike(f'%{search_query}%')).all()
            return render_template('search_users.html', users=users)
    return redirect(url_for('home'))
    
@user.route('/profile/<int:user_id>', methods=['GET', 'POST'])
def profile(user_id):
    print('profile')
    if 'user_id' in session:
        user = User.query.get(user_id)
        friend_requests_received = FriendRequest.query.filter_by(receiver_id=user_id, status='pending').all()
        # find friends
        friendsAccepted = FriendRequest.query.filter_by(sender_id=user_id, status='accepted').all()
        friends = User.query.filter(User.id.in_([friend.receiver_id for friend in friendsAccepted])).all()
        if request.method == 'POST':
            sender_id = user.id
            receiver_username = request.form['receiver_username']
            receiver = User.query.filter_by(username=receiver_username).first()
            if receiver:
                # Verificar si ya existe una solicitud pendiente entre los usuarios
                existing_request = FriendRequest.query.filter_by(sender_id=sender_id, receiver_id=receiver.id).first()
                if not existing_request:
                    new_request = FriendRequest(sender_id=sender_id, receiver_id=receiver.id)
                    db.session.add(new_request)
                    db.session.commit()
        return render_template('profile.html', user=user, friend_requests_received=friend_requests_received, friends=friends, random=random)
    else:
        return redirect(url_for('auth.login'))
    
@user.route('/send_friend_request/<int:receiver_id>', methods=['POST'])
def send_friend_request(receiver_id):
    if 'user_id' in session:
        sender_id = session['user_id']
        friend_request = FriendRequest(sender_id=sender_id, receiver_id=receiver_id)
        db.session.add(friend_request)
        db.session.commit()
    return redirect(url_for('home'))

@user.route('/accept_friend_request/<int:request_id>', methods=['POST'])
def accept_friend_request(request_id):
    if 'user_id' in session:
        user_id = session['user_id']
        friend_request = FriendRequest.query.get(request_id)
        if friend_request and friend_request.receiver_id == user_id:
            friend_request.status = 'accepted'
            db.session.commit()
    return redirect(url_for('home'))

@user.route('/reject_friend_request/<int:request_id>', methods=['POST'])
def reject_friend_request(request_id):
    if 'user_id' in session:
        user_id = session['user_id']
        friend_request = FriendRequest.query.get(request_id)
        if friend_request and friend_request.receiver_id == user_id:
            friend_request.status = 'rejected'
            db.session.commit()
    return redirect(url_for('home'))

app/templates/app.html
<html lang="es" data-theme="light">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{% block title %}App{% endblock %}</title>

    <link
      href="https://cdn.jsdelivr.net/npm/daisyui@4.10.2/dist/full.min.css"
      rel="stylesheet"
      type="text/css"
    />

    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='css/style.css') }}"
    />
  </head>
  <body>
    {% include 'components/navbar.html' %}
    <div class="flex flex-col min-h-screen">
      <div class="flex-grow">{% block content %} {% endblock %}</div>

      {% include 'components/footer.html' %}
    </div>
  </body>

  <link
    href="{{ url_for('static', filename='css/main.css') }}"
    rel="stylesheet"
  />
</html>

app/templates/home.html
{% extends 'app.html' %} {% block title %} 🛩️ SkyTech | App {% endblock %} {%
block content %}
<div
  class="bg-fixed bg-cover"
  style="background-image: url('{{ url_for('static', filename='img/aircraft.png') }}'); "
>
  <div class="flex flex-col items-center justify-center min-h-screen p-4">
    <div class="max-w-3xl mx-auto text-center">
      <h1 class="text-8xl font-bold mb-4">
        Find Your Flight
        <span
          class="bg-clip-text text-transparent bg-gradient-to-r from-blue-400 to-green-400"
          >Easily</span
        >
      </h1>
      <br /><br />
      <form
        action="{{ url_for('search_flights.search') }}"
        method="post"
        class="flex justify-center"
      >
        <div class="form-control">
          <div class="relative">
            <label
              class="input input-bordered flex items-center input-lg w-full max-w-xs"
            >
              <input
                type="text"
                name="search"
                id="search"
                class="grow input-lg w-full max-w-xs"
                placeholder="Search your flight ...."
              />
              <svg
                xmlns="http://www.w3.org/2000/svg"
                viewBox="0 0 16 16"
                fill="currentColor"
                class="w-4 h-4 opacity-70"
              >
                <path
                  fill-rule="evenodd"
                  d="M9.965 11.026a5 5 0 1 1 1.06-1.06l2.755 2.754a.75.75 0 1 1-1.06 1.06l-2.755-2.754ZM10.5 7a3.5 3.5 0 1 1-7 0 3.5 3.5 0 0 1 7 0Z"
                  clip-rule="evenodd"
                />
              </svg>
            </label>
          </div>
        </div>
      </form>
    </div>
  </div>
</div>
{% endblock %}

app/templates/login.html
<!DOCTYPE html>
<html lang="es" data-theme="light">
  <head>
    <meta charset="UTF-8" />
    <title>🛩️ SkyTech | Login</title>
    <link
      href="https://cdn.jsdelivr.net/npm/daisyui@4.10.2/dist/full.min.css"
      rel="stylesheet"
      type="text/css"
    />
    <link
      href="{{ url_for('static', filename='css/main.css') }}"
      rel="stylesheet"
    />
  </head>
  <body
    class="flex items-center justify-center h-screen bg-gradient-to-r from-primary to-purple-600"
  >
    <div class="container max-w-md mx-auto text-center">
      <div class="card bg-base-100 shadow-xl">
        <div class="card-body">
          <h2 class="text-4xl font-bold text-center">Login</h2>
          <form action="{{ url_for('auth.login') }}" method="post" class="mt-4">
            <div class="form-control">
              <label class="label">
                <span class="label-text">Username</span>
              </label>
              <div class="relative">
                <input
                  type="text"
                  id="username"
                  name="username"
                  class="input input-bordered w-full pr-10"
                  required
                />
                <svg
                  xmlns="http://www.w3.org/2000/svg"
                  viewBox="0 0 16 16"
                  fill="currentColor"
                  class="w-4 h-4 opacity-70 absolute inset-y-0 right-3 my-auto"
                  fill-rule="evenodd"
                >
                  <path
                    d="M8 8a3 3 0 1 0 0-6 3 3 0 0 0 0 6ZM12.735 14c.618 0 1.093-.561.872-1.139a6.002 6.002 0 0 0-11.215 0c-.22.578.254 1.139.872 1.139h9.47Z"
                  />
                </svg>
              </div>
            </div>
            <div class="form-control mt-4">
              <label class="label">
                <span class="label-text">Password</span>
              </label>
              <div class="relative">
                <input
                  type="password"
                  id="password"
                  name="password"
                  class="input input-bordered w-full pr-10"
                  required
                />
                <svg
                  xmlns="http://www.w3.org/2000/svg"
                  viewBox="0 0 16 16"
                  fill="currentColor"
                  class="w-4 h-4 opacity-70 absolute inset-y-0 right-3 my-auto"
                >
                  <path
                    fill-rule="evenodd"
                    d="M14 6a4 4 0 0 1-4.899 3.899l-1.955 1.955a.5.5 0 0 1-.353.146H5v1.5a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1-.5-.5v-2.293a.5.5 0 0 1 .146-.353l3.955-3.955A4 4 0 1 1 14 6Zm-4-2a.75.75 0 0 0 0 1.5.5.5 0 0 1 .5.5.75.75 0 0 0 1.5 0 2 2 0 0 0-2-2Z"
                    clip-rule="evenodd"
                  />
                </svg>
              </div>
            </div>
            <button type="submit" class="btn btn-primary btn-block mt-6">
              Login
            </button>
          </form>
        </div>
      </div>
      <div class="text-center text-white">
        <p>
          Don't have an account?
          <a href="{{ url_for('auth.signup') }}" class="link">Sign up</a>
        </p>
      </div>
    </div>
  </body>
</html>

app/templates/profile.html
{% extends 'app.html' %} {% block title %} 🛩️ SkyTech | Profile {% endblock %}
{% block content %}

<div class="container mx-auto p-4">
  <h1 class="text-2xl font-bold mb-4">User Profile</h1>
  <div class="bg-white shadow-md rounded-lg p-6 mb-4">
    <p><strong>Username:</strong> {{ user.username }}</p>
    <p><strong>Name:</strong> {{ user.first_name }} {{ user.last_name }}</p>
    <p><strong>Email:</strong> {{ user.email }}</p>
    <p><strong>Phone:</strong> {{ user.phone }}</p>
  </div>

  <!-- Formulario de búsqueda de usuarios -->
  <div class="bg-white shadow-md rounded-lg p-6 mb-4">
    <h2 class="text-xl font-semibold mb-4">Search Users</h2>
    <form
      action="{{ url_for('user.search_users') }}"
      method="post"
      class="flex gap-2 items-center"
    >
      <input
        type="text"
        name="search_query"
        placeholder="Search users by username"
        class="input input-bordered w-full max-w-xs"
      />
      <button type="submit" class="btn btn-primary">
        <svg
          xmlns="http://www.w3.org/2000/svg"
          fill="none"
          viewBox="0 0 24 24"
          stroke-width="1.5"
          stroke="currentColor"
          class="w-6 h-6"
        >
          <path
            stroke-linecap="round"
            stroke-linejoin="round"
            d="M15.75 10.5a5.25 5.25 0 11-10.5 0 5.25 5.25 0 0110.5 0zm0 0l4.5 4.5"
          />
        </svg>
        Search
      </button>
    </form>
  </div>

  <!-- Solicitudes de amistad recibidas -->
  <div class="bg-white shadow-md rounded-lg p-6 mb-4">
    <h2 class="text-xl font-semibold mb-3">Friend Requests Received</h2>
    {% if friend_requests_received %}
    <ul>
      {% for request in friend_requests_received %}
      <li class="flex justify-between items-center mb-2">
        {{ request.sender.username }} sent you a friend request
        <div>
          <form
            action="{{ url_for('user.accept_friend_request', request_id=request.id) }}"
            method="post"
            class="inline"
          >
            <input type="submit" value="Accept" class="btn btn-success" />
          </form>
          <form
            action="{{ url_for('user.reject_friend_request', request_id=request.id) }}"
            method="post"
            class="inline"
          >
            <input type="submit" value="Reject" class="btn btn-error" />
          </form>
        </div>
      </li>
      {% endfor %}
    </ul>
    {% else %}
    <p>No friend requests</p>
    {% endif %}
  </div>

  <!-- Lista de amigos -->
  <div class="bg-white shadow-md rounded-lg p-6">
    <h2 class="text-xl font-semibold mb-3">Friend List</h2>
    {% if friends %}
    <ul>
      {% for friend in friends %}
      <li>{{ friend.username }}</li>
      {% endfor %}
    </ul>
    {% else %}
    <p>No friends</p>
    {% endif %}
  </div>
</div>

{% endblock %}

app/templates/search_history.html
{% extends 'app.html' %} {% block title %} 🛩️ SkyTech | Flights {% endblock %}
{% block content %}
<div
  class="bg-gradient-to-r from-primary to-purple-600 min-h-screen flex items-center justify-center"
>
  <div class="container mx-auto px-4 py-5 bg-white shadow rounded-lg">
    <h1 class="text-center text-2xl font-bold mb-5">Search History</h1>
    <p>Welcome, {{ user.username }}!</p>
    <table class="table-auto w-full mt-3">
      <thead>
        <tr>
          <th class="px-4 py-2 text-left">Origin</th>
          <th class="px-4 py-2 text-left">Destination</th>
          <th class="px-4 py-2 text-left">Departure Date</th>
          <th class="px-4 py-2 text-left">Arrival Date</th>
        </tr>
      </thead>
      <tbody>
        {% for search in searches %}
        <tr>
          <td class="border px-4 py-2">{{ search.origin }}</td>
          <td class="border px-4 py-2">{{ search.destination }}</td>
          <td class="border px-4 py-2">{{ search.departure_date }}</td>
          <td class="border px-4 py-2">{{ search.return_date }}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
    <div class="text-center mt-5">
      <a
        href="{{ url_for('home') }}"
        class="btn bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded"
      >
        Back to Main Menu
      </a>
    </div>
  </div>
</div>
{% endblock %}

app/templates/search_users.html
{% extends 'app.html' %} {% block title %} 🛩️ SkyTech | Profile {% endblock %}
{% block content %}

<div class="container mx-auto mt-8">
  <h1 class="text-2xl font-bold mb-3">Search Results</h1>

  {% if users %}{% for user in users %}
  <div class="flex justify-between items-center p-4 bg-base-100 rounded-box">
    <span>{{ user.username }}</span>
    <form
      action="{{ url_for('user.send_friend_request', receiver_id=user.id) }}"
      method="post"
      class="inline"
    >
      <button class="btn">Send Friend Request</button>
    </form>
  </div>
  {% endfor %} {% else %}
  <span>No users found</span>
  {% endif %}
</div>

{% endblock %}

app/templates/signup.html
<!DOCTYPE html>
<html lang="es" data-theme="light">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>🛩️ SkyTech | Register</title>
    <link
      href="https://cdn.jsdelivr.net/npm/daisyui@4.10.2/dist/full.min.css"
      rel="stylesheet"
      type="text/css"
    />
    <link
      href="{{ url_for('static', filename='css/main.css') }}"
      rel="stylesheet"
    />
    <style>
      @keyframes moveGradient {
        0% {
          background-position: 0% 50%;
        }
        50% {
          background-position: 100% 50%;
        }
        100% {
          background-position: 0% 50%;
        }
      }
      body {
        background: linear-gradient(270deg, #6ee7b7, #3b82f6, #9333ea);
        background-size: 600% 600%;
        animation: moveGradient 10s ease infinite;
      }
    </style>
  </head>
  <body class="flex items-center justify-center min-h-screen">
    <div class="container bg-white p-8 rounded-lg shadow-lg max-w-md">
      <h1 class="text-center text-3xl font-bold mb-6">Regístrate</h1>
      <p class="text-center mb-6">Ingresa tus datos</p>
      <form action="{{ url_for('auth.signup') }}" method="post">
        <div class="form-control mb-4">
          <input
            type="text"
            name="name"
            placeholder="Nombre"
            class="input input-bordered w-full"
          />
        </div>
        <div class="form-control mb-4">
          <input
            type="text"
            name="surname"
            placeholder="Apellido"
            class="input input-bordered w-full"
          />
        </div>
        <div class="form-control mb-4">
          <input
            type="email"
            name="email"
            placeholder="Correo electrónico"
            class="input input-bordered w-full"
          />
        </div>
        <div class="form-control mb-4">
          <input
            type="text"
            name="username"
            placeholder="Nombre de usuario"
            class="input input-bordered w-full"
          />
        </div>
        <div class="form-control mb-4">
          <input
            type="text"
            name="phone"
            placeholder="Teléfono"
            class="input input-bordered w-full"
          />
        </div>
        <div class="form-control mb-6">
          <input
            type="password"
            name="password"
            placeholder="Contraseña"
            class="input input-bordered w-full"
          />
        </div>
        <button type="submit" class="btn btn-primary w-full">
          Crear cuenta
        </button>
      </form>
      <div class="text-center">
        <p>
          Already have an account?
          <a href="{{ url_for('auth.login') }}" class="link">Login</a>
        </p>
      </div>
    </div>
  </body>
</html>